### ISSUE TITLE
currently not working for me

### ISSUE THREAD

**Issue by christianflickr** [stvedt/Flickr-Automated-Unfollow#13] opened 2017-04-20 15:10 UTC
Hi, thanks first for this amazing tool! I use it quite often.
Are you experiencing the same problem? 
The script isn't doing anything at the moment for me....

**Comment by koperman** [comment] 2017-04-21 07:04
Hello,
Yes Inhave got the same issue/problem, even with the old version : they don't work anymore until now. 
Maybe changes from Flickr recently ?

**Comment by christianflickr** [comment] 2017-04-21 12:33
Thanks for answering! 
Not that I am aware of. 
They introduced a new search algorithm/option. 
https://code.flickr.net/

I by myself only understand parts of the code you wrote, many thanks for that btw, so I can't search for the problem nor fix it. 

Have a great weekend!

**Comment by koperman** [comment] 2017-04-21 14:53
Dear Christian,  I'm a user as your are, waiting for stevdt the developer to answer and maybe to find a solution to fix it.

Have a great weekend too. 

Koperman

**Comment by stvedt** [comment] 2017-04-21 15:45
Hey everyone,
This is on my to do list to look into what may have changed on flickr's side that would be affecting the script. I'll update here as I discover what may be the cause.

Best,
Stephen

**Comment by koperman** [comment] 2017-04-21 16:02
Thanks a lot Stephen !
BR
Koperman

**Comment by christianflickr** [comment] 2017-04-21 17:37
Stephen, that would be really great! Thanks a lot!

**Comment by stvedt** [comment] 2017-04-26 12:51
I have found the issue. It is because I am injecting jquery onto the page. So I am going to be eliminating my dependency on using jQuery. Look for an update in a day or two.

**Comment by koperman** [comment] 2017-04-26 12:56
Thanks a lot Stephen for your quick answer and solution !
Have a nice afternoon !

Koperman.

**Comment by apgr** [comment] 2017-04-27 18:27
+1 on the thanks and appreciation - this is a really useful script

**Comment by stvedt** [comment] 2017-04-30 14:25
Hey everyone, I have resolved the issue. Please check the latest code on the master branch. Fix merged in #14

**Closed by stvedt** 2017-04-30 14:25 UTC

**Comment by koperman** [comment] 2017-05-01 07:44
Many thanks Stephen ! I will be back home on Friday to check the update. 
Have a nice week.
Best Regards. Koperman. 

Envoyé de mon iPad

**Comment by apgr** [comment] 2017-05-03 07:02
Working for me now 

 

Thanks!!!
